### ISSUE TITLE
Version history

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#100]
Yet another idea. To use up the space under the map in every project sheet, would it be possible to add a version history? A simple "this catalogue record was last updated on DD MM YYYY" might be enough.

 Is it doable? I think it would add to the quality of the data itself.

**Comment by csae8092** [comment]
To provide such information we'd need to store date stamps (created, last modified) for each edition object. This is basically no big deal, though in case of dig-ed-cat I'm a reluctant because the version history of the data is already documented through GitHub. By doing so we are leveraging GitHubs core functionality and are not in the need to duplicate functionality (and bloating up the code-base of our application)

**Comment by gfranzini** [comment]
OK.
