### ISSUE TITLE
get the data in rdf

### ISSUE THREAD

**Issue by zxenia** [acdh-oeaw/dig_ed_cat#124]
Hi guys,
I tried to map the data to rdf schema and dublin core. I added a separate view for rdf/xml.
It's not public yet since the mapping should be thought through more and not finished yet.
You can see it when you logged in under get the data -> rdf/xml.
Any comments and modelling suggestions are very welcome!
I also want to create the same view for bibtex format since it can be easily imported in zotero.

**Comment by gfranzini** [comment]
This is awesome Ksenia, thank you! Here are some initial observations/questions from my side:

- I opened the XML in Oxygen and I get validation errors because of the ampersand symbols, which should be coded to `&amp;` to fix the issue. Should these be corrected? 
- As for the data mapping. Can you post the Dublin Core list of elements you're referring to, so that I can check whether there is anything else we can map?
- Is this a dynamic file? What I mean is, will this file also be automatically updated when the data is synched in GitHub? 
- Visualisation: were you also thinking of visualising the RDF data? Something along the lines of [LodLive](http://en.lodlive.it) or [Cytoscape](http://cytoscape.org/what_is_cytoscape.html), maybe?

I also love the idea of a bibtex format for Zotero.

Very exciting developments, thank you!! :-D

**Comment by zxenia** [comment]
Hi Greta!
1. Thanks for noticing this! I'll look into it.
2. For now I just used [dublin core elements set](http://dublincore.org/documents/dces/), but we can extend with [dublin core terms](http://dublincore.org/documents/dcmi-terms/). How I mapped it to dig-ed-cat data model, you can see in this [xml template](https://github.com/acdh-oeaw/dig_ed_cat/blob/master/browsing/templates/browsing/xml_template.xml). 
Let say mapping to dublin core is a basic mapping. This data can be reused by libraries if they like to add the data to their catalogues because dublin core is very widespread standard. We can (and should) extend  it and include other[ LOD vocabularies](http://lov.okfn.org/dataset/lov/), like geonames for locations. 
3. Correct. This is not a static file, it's generated everytime when you call it, and script triggers all objects in database.
4. Yes, we can try. thanks for links! I'll check them.
Thank you!

**Comment by zxenia** [comment]
also the mapping is very basic now (just for testing the output), I was more curious to implement technical solution first :)

**Comment by csae8092** [comment]
Awesome feature! 
Though I'd suggest to use some dedicated library to produce the RDF graph like [rdflib](https://rdflib.readthedocs.io/en/stable/). This will allow us to 

1. present the RDF data in various formats (e.g. XML/RDF, ttl, ...),
2. but maybe even more important, such a library makes sure, that the data we produce is actually valid (which might not always be the case for 'hand made' RDF/XML). 

For the mapping: Since we are currently anyway defining some kind of [ACDH-Ontology](https://github.com/acdh-oeaw/repo-schema) for our soon to be ready ACDH-Repo, maybe we should try to map the catalog data against the ACDH-Ontology

**Comment by gfranzini** [comment]
I'm all for valid data, so rdflib gets my vote. Mapping the cat against the ACDH ontology also makes sense!
In terms of LOD vocabularies, to start we could link to:
- **Time**: http://lov.okfn.org/dataset/lov/vocabs/time
- **CC**: https://creativecommons.org/ns
- **Prov**: https://www.w3.org/ns/prov# (For institutions responsible for the editions)
- **Geonames**: http://www.geonames.org/ontology/documentation.html#geonamesID

Thoughts?

**Comment by zxenia** [comment]
Hi ! I will try to use RDFlib for rdf/xml output.
I mapped to bibtex, and tried to import bibtex output in Zotero. I was able to import all editions in Zotero library. The only thing is that in order to preserve more information for Zotero, items were imported as 'book' type in Zotero, but I added a tag 'digital edition'. If we'd map it to 'web page' type then we cannot save information like publisher (institutions) since there is no this field for web page type.

About the vocabularies:
good suggestions! I had a thought today maybe we could collect urls for universities? then our rdf:about would point to a web presence of university.
question about time ontology: Greta, you think we need it for historical periods?

**Comment by gfranzini** [comment]
Fantastic, thank you so much!! 
Good solution for Zotero, I don't see a better option. I was actually reading the Zotero documentation to see whether it is possible to add a new item type, but apparently not: http://forums.zotero.org/discussion/15636/1/changes-to-fields-and-item-types-for-zotero-31-/  (scroll down to 'Custom fields'/item types'). I can document this limitation once we make this feature publicly available. We should also add the [Zotero logo](https://www.zotero.org/support/brand) to the website.

Regarding the time ontology and historical periods. The best option I was able to find until now is to use the `time:GeneralDurationDescription` class with the `time:years` property. See [here](https://www.w3.org/TR/owl-time/#time:years).
DBPedia has something more specific to [historical periods](http://dbpedia.org/ontology/HistoricalPeriod) but I'm not sure I fully understand it.

As for institution URLs. Of course! Where would I add these? To the institutions .csv file or somewhere else?

**Comment by csae8092** [comment]
> As for institution URLs. Of course! Where would I add these? To the institutions .csv file or somewhere else?

Yes, simply add a new column to [institutions.csv](https://github.com/gfranzini/digEds_cat/blob/master/institutions_places_enriched.csv) ideally after `type of location`, maybe call it something like 'institution website'.

**Comment by gfranzini** [comment]
OK!

**Comment by gfranzini** [comment]
Hi, I added institution websites and synched the data. FYI, two institutions don't have a URL.

**Comment by gfranzini** [comment]
Also found this: https://www.w3.org/TR/vocab-dcat/

Let me know if there's something I can do here (for example, map the Catalogue data against a particular property or category in any of the vocabularies we're using).

**Comment by zxenia** [comment]
Hi,
I looked into dcat vocabulary. Good idea I think, since our edition was missing rdf:type. So then each digital edition will be dcat:CatalogRecord or dcat:Dataset? I am a bit confused since Dataset class actually has all the properties from dc terms which we are using.

Regarding mapping: I mapped institutions to foaf:Organization and places to gn:Feature and geo:SpatialThing. And just pulled the last version to the server so you can see how [rdf looks like now](https://dig-ed-cat.acdh.oeaw.ac.at/browsing/rdf/).

The problem I have is about Periods. Seems rather complicated to me. Maybe you look into it.

Another thing is about creative commons license: we only have yes/no, but not the type of the license which would then make sense to use this in rdf and link to directly cc license online. So for now there is only dc:rights which store data from open_source field.

**Comment by gfranzini** [comment]
Hi Ksenia, this is awesome! 
I can look into Periods, no problem. I haven't been able to spend much time on the project this month as I've been busy writing up the paper on the Cat survey that I sent around in the spring. I'll resume work here as soon as that's out of the way! 
Could you perhaps assign this ticket to me so that I can more easily find it later?

Thanks!!

**Comment by zxenia** [comment]
great! thanks!

> Could you perhaps assign this ticket to me so that I can more easily find it later?

I discovered that I actually can't do it, I only can assign people who are members of acdh-oeaw organization (strange).

**Comment by gfranzini** [comment]
OK, no problem!

**Comment by zxenia** [comment]
I added download in formats n3 and rdf/xml for selected editions. When we decide what to do with Periods, I'll update rdf schema. I also opened Bibtex format download for non-auth users.

**Comment by gfranzini** [comment]
Wonderful, I'll advertise it tomorrow! I hope to find some time this week to study the Periods issue.

**Comment by csae8092** [comment]
@zxenia: Awesome!!!!
though one minor thing: can we change the icons a bit, maybe only one download button which expands 'on click' into data-format specific icons?

**Comment by zxenia** [comment]
Hi, I' ll rework then this download button.

@gfranzini ,
for periods you can also look into this gazetteer http://perio.do/, maybe we can somehow link our periods to Periodo.

**Comment by gfranzini** [comment]
Interesting, thanks! Will look into it.

**Comment by gfranzini** [comment]
Hi @zxenia and @csae8092 ! So I studied the [Perio.do Gazetteer](http://perio.do/) and this is the closest mapping I could create between the Cat and Perio.do.

Catalogue | Perio.do | Collection
------------ | ------------- | -------------
Antiquity [700BC-500AD] | http://n2t.net/ark:/99152/p0qhb66qj4c [-600-499] | [ARIADNE](http://www.ariadne-infrastructure.eu/Resources/PeriodO/documentation)
Middle Ages [500-1500] | http://n2t.net/ark:/99152/p0pqptcfq9t [450-1500] | [ARIADNE](http://www.ariadne-infrastructure.eu/Resources/PeriodO/documentation)
Early Modern [1500-1789] | http://n2t.net/ark:/99152/p0qhb66kxnr [1500-1789] | [ARIADNE](http://www.ariadne-infrastructure.eu/Resources/PeriodO/documentation)
Long Nineteenth Century [1789-1914] | http://n2t.net/ark:/99152/p086kj9tqzk [1800-1900] | [Anderson Digital Index](http://ux.opencontext.org/archaeology-site-data/)
Modern [1914-1965] | http://n2t.net/ark:/99152/p0dg76fcnx9 [1878-1949]| [Pyla-Koutsopetria archaeological survey](https://opencontext.org/types/36714472-FC5D-4B19-5047-1BB3F6545280)
Contemporary [1965-today] |  http://n2t.net/ark:/99152/p0qhb66d849 [1945-2000] | [ARIADNE](http://www.ariadne-infrastructure.eu/Resources/PeriodO/documentation)

The ARIADNE mapping works almost perfectly, the mapping for 19th CENTURY and MODERN doesn't.

What do we do? 
What happens when we have multiple periods for one project? We would just add two Perio.do URLs?

**Comment by zxenia** [comment]
Hi,
this looks good.
Actually there is already a field 'PeriodO id' in database for storing this identifier.
I have a question:  in database some periods are a combination of periods (e.g. 'Early Modern; Long Nineteenth Century; Modern; Contemporary' - this is one period in database). so how do we deal with this?

**Comment by csae8092** [comment]
>  We would just add two Perio.do URLs?

possible, but imho not a very nice solution because I'd say only a 1:1 relation between a concept like a periode and it's identifier makes much sense. 

To deal with combination of periods we can either
* change the datamodel so that one entry (edition) can be linked to several periods, or
* keep the data(model) as it is and register the missing 'periods' in period.io.

I'd go for the second solution because I think something like 

> Early Modern; Long Nineteenth Century; Modern; Contemporary 

constitutes its own period in our data. 
Plus the second solution is also easier to implement

**Comment by gfranzini** [comment]
@csae8092 by "register our periods in perio.do" you mean adding it to their database, right? I had a look at their website again and I can't seem to find information about adding a new period.

**Comment by csae8092** [comment]
yes, I thought this would be possible....

**Comment by csae8092** [comment]
@zxenia and @gfranzini 
should we close this issue? because `get the data in rdf` is basically implemented....

**Comment by gfranzini** [comment]
we can close it!
