### ISSUE TITLE
Chart fixes

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#132]
- The values of the Creative Commons chart are still numerical. Can they be changed to 'no', 'yes' and 'partially'?
- Writing support/Infrastructure/Audience/Language charts: can the values here be better itemised or separated? I think this is needed for the chart to really work. At the moment we have duplicates across strings that combine different supports, like: 'Archival document; Manuscript; Printed book'. In the chart, would it be possible to lose these combinations and make sure that there is only one support per line on the Y axis? So, basically, 'Archival document; Manuscript; Printed book' would become three separate items, one per line thus removing redundancy. I could then add an explanatory paragraph above the charts explaining that a project can be drawing from multiple supports, using multiple technologies and addressing multiple audiences.
- Website language: The Y axis contains strange numerical values.
- Open Source/Access: can I replace the values on the Y axis with something more descriptive or add a legend above the charts?

**Comment by csae8092** [comment]
> The values of the Creative Commons chart are still numerical. Can they be changed to 'no', 'yes' and 'partially'?

This is actually a matter of the database schema because it stores the numerical values and not the 'labels'. I'll change this systematically but this means some change in the data model, sync-script and presumable in the filters as well as templates. So it will take some time...

>Writing support/Infrastructure/Audience/Language charts: can the values here be better itemised or separated?...

This is more a data issue which could be solved during synchronization and some bigger changes in the applications data model and therefore will need some time.

> Website language: The Y axis contains strange numerical values

I'm aware of this but frankly I can't explain this behavior right now... . So further investigation on my side is needed 

> Open Source/Access: can I replace the values on the Y axis with something more descriptive or add a legend above the charts?

I'm currently working on a more handy solution to configure charts ([see here](https://github.com/acdh-oeaw/dig_ed_cat/issues/134)) and ideally this should fix this
