### ISSUE TITLE
minor layout issues due to updates

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/dig_ed_cat#201]
after selecting an autocomplete suggestion, but maybe there are other issues as well...

**Comment by zxenia** [comment]
This is a real issue, and it looks really bad now.  Don't really know what dependency was broken with this update, but on another project, I use same versions of all libs except of Bootstrap (here we use Bootstrap 3.5 + some bootstrap theme I think). Anyway, I guess the update of dal module caused that because it provides select2.css for multiple select field. Found also similar issue [here](https://github.com/yourlabs/django-autocomplete-light/issues/1055).
