### ISSUE TITLE
Edition maps with multiple institutions

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#21]
Not sure if you have this on your to-do list already, but the maps for editions with multiple institutions don't provide location markers. I see three options:
1. Display the location of the main institution only (which I always put first in the relevant Catalogue field);
2. Display them all;
3. Display them all, the main one in blue and the others in a lighter shade of blue or another colour.

Not sure what's easiest for you, but I would favour option 2 or 3. Option 3 would be nice but I don't want to make any incorrect judgements regarding how much work each institution contributed to the edition, so option 2 would probably be the best solution.

Thoughts?

**Comment by csae8092** [comment]
I was aware that there are some issues with the maps but I didn't invest any time/thoughts into it so far. I would prefere option number three because it is easier to implement and the danger of insulting someone is not so present. 
I quickly tried to collected some samples of what when who shows up. 

## not all institutions
https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/detail/109
https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/detail/106
https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/detail/103

## no institution
https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/detail/107

The reason why not all institutions are showing up is related to missing coordinates. E.g. "Southeastern Louisiana University" which is involved in https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/detail/103 does not show up (unlike "British Library"). When you look at the data provided for those institutions (https://raw.githubusercontent.com/gfranzini/digEds_cat/master/digEds_cat_spatial.csv) you'll see that there are no coordinates provided for "Louisana University", actually "Louisana University" is not on the list. I'd suggest starting with this list (https://dig-ed-cat.eos.arz.oeaw.ac.at/editions/institution-csv/) to check the institutions (the automatically enriched GND-ID) and add coordinates.

**Comment by gfranzini** [comment]
I've been updating the digEds_cat_spatial.csv today. I'll commit the changes later today.
OK for option 3. As I said, Option 3 is the nicest but I hope nobody will sue me for it :-P Thank you!

**Comment by csae8092** [comment]
I'd go now for option 2. Because

- it this option is already implemented 
- in case of two institutions it would be clear, which one is the "main" institution
- I don't wont to fiddle around too much with leaflets-api for now

I close this issue - if you contradict, please reopen it

**Comment by gfranzini** [comment]
Fine by me! Issue closed.
