### ISSUE TITLE
Edition count

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#24]
The edition count you have at the bottom of the BROWSE EDITIONS page should be reduced by 1 because the first row in the Catalogue is for the column headers.

**Comment by csae8092** [comment]
Header, Footer and blank lines in [source file](https://github.com/gfranzini/digEds_cat/blob/master/digEds_cat.csv) are now ignored by sync-script.
But there is still one edition two much in the database. One reason for this might be, that deletions in the source file are not reflected by the sync-script which only checks if an edition with the given name already exists in the database and if yes:
* updates the already existing entry
* creates a new entry
This raises the question if editions can/should be deleted and how to deal with deleted editions

**Comment by csae8092** [comment]
https://dig-ed-cat.eos.arz.oeaw.ac.at/charts/barcharts/?chart=/charts/editionspercountryjson/
https://dig-ed-cat.eos.arz.oeaw.ac.at/charts/piecharts/?chart=/charts/editionspercountryjson/

but be aware that the charts only reflect editions, which are related to institutions from which the gps-coordinates are known

**Comment by gfranzini** [comment]
Related issue: the app doesn't display the last edition added but the second before last. For example, if I add EDITION 230 and sync, the app will only display editions up to EDITION 229. EDITION 230 is displayed once I add EDITION 231, and so on.

**Comment by csae8092** [comment]
now all editions should be synced.

**Comment by gfranzini** [comment]
Yes, super! Thanks :-)

**Comment by gfranzini** [comment]
There are still issues here. The app says it has 235 editions when it has 230. I *think* what's happening is that new syncs are interpreted as the addition of new editions. In my last sync, for example, I only pushed updates to existing editions, no new edition. But the message I got after syncing suggested I added two new editions, which wasn't the case. 
I'm not bothered about the information I get when I sync, but the edition count is inaccurate.

No rush, just wanted to flag it up!

**Comment by csae8092** [comment]
Due to the lack of some stable IDs in the data I used the editions URL as identifier for the import script. 
`temp_ed, _ = Edition.objects.get_or_create(url=row[3])`
So the scripts checks if there is already an Edition object with an URL 'xyz' in the database and if yes, it updates it overwrites any already stored properties with the new ones fetched from your list. 
But if the URL changes, it simply creates a new edition-object which is then basically a duplication of an the already existing one. 
To fix this,
1.  we could use the row Id from your list as stable ID. 
2. keep everything as it is and just delete duplicates (either manually or by a simply 'post-sync' script 

I'd opt for the first option if you can guarantee to keep the order of the editions stable (which shouldn't be too hard, since new editions will be added at the bottom anyway, and with the DEAD/ALIVE field there is no need to kick out non existing editions)

**Comment by gfranzini** [comment]
Agreed! I haven't been changing the order of the editions, but I did update a couple of broken links this week. I will keep adding editions at the bottom of the list.
