### ISSUE TITLE
URLs in target="_blank"

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#27]
Would it be possible to open all URLs in new tabs? That way the Catalogue is not "lost" but still available in a separate tab.

**Comment by csae8092** [comment]
Of course this is be possible. But personally I am not a big fan of "_blank" because it takes the choice form the user (me). But since not all users are familiar with "ctrl+click" to open a link in a new tab, I am thinking of adding some icon next to the link with a title like "open link in new tab".

**Comment by gfranzini** [comment]
sounds good!
