### ISSUE TITLE
Page browsing

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#29]
Hi! following some user feedback communicated to me verbally, would it be possible to: 

- change the colour of the "Page 1 of 10 25 of 226 editions / Next/Previous" text to something darker? People with poorer vision struggle to see it. 
- change the current next/previous system to the system that Amazon, for example, uses? Some users of the catalogue would prefer to jump to/from specific pages rather than press the next/previous buttons until they get to the desired page.

**Comment by csae8092** [comment]
The second request would need some thinking and programming (which we don't really have the resources  right now) especially because this request doesn't make too much sense for me, because users don't know which editions are listed on what page anyway and they are provided with sort/filter functionality already. 
As far as visibility is concerned, yes that's definitely an issue, one maybe @zxenia can fix by providing a short css-snippet for the concerned html-elements
```<ul class="pagination">```

**Comment by zxenia** [comment]
I added a pagination to the browse catalogue view [revision](https://github.com/acdh-oeaw/dig_ed_cat/commit/0961ebd32c43e8c47aa778c46256997ba96631e7).
And rearrange links in navbar a bit, hope it is more explicit now where the catalogue is.

**Comment by gfranzini** [comment]
Thank you, this solution is perfect! Nice.
