### ISSUE TITLE
Begin and End date

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#52]
Hi, the 'Begin' and 'End' date columns are complete now (no empty cells). Would it be possible to make sure that the values 'present' and 'not provided' are displayed in the app?
Thanks!

**Comment by csae8092** [comment]
this is actually a bit tricky because the dates are actually stored as date objects. While importing the script simply checks if the string in the csv-field can be parsed as a date object and if not, the field stays blank. I will look into to come up with some dirty workaround. Though this may take some time

**Comment by gfranzini** [comment]
A workaround would be great but take all the time you need.
