### ISSUE TITLE
Updates to CC license field

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#65]
The description and values of the CC license field need updating. 

1. New field description (by this I mean the text that appear when clicking the information 'i' button): **This field specifies if the project is protected by a Creative Commons License.**

2. The number-text value mapping of the CC field is:
* not provided - not provided
* 0 - no
* 0.5 - partial
* 1 - yes
Could we display the _text_ values rather than the number values (with the exception of "not provided" of course, which doesn't apply)? Ideally, we would have text values for all fields in the catalogue for consistency but I will create separate issues for each of those.

**Comment by csae8092** [comment]
As you can see [here](https://github.com/acdh-oeaw/dig_ed_cat/commit/f88d10808267eb2355974bc2fb872deab1ebf37c) the second part of your request ( "display the text values rather than the number") is implemented very easy. So I`d suggest you just post a list of all fields where you want to have the string values displayed to this issue, or you change the code and create a pull request.

**Comment by csae8092** [comment]
ok, since I am already on it, I'll change it myself....

**Comment by gfranzini** [comment]
Thanks, I will do PR for the others as you suggest.

**Comment by csae8092** [comment]
they should be implemented already
