### ISSUE TITLE
Scrollable news

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#89]
First of all, I **really** like the new news solution you implemented on the homepage. Bigger and clearer! Thanks a lot for this!
Feature request: as more news appears (I will try to publish monthly posts), would it be possible to add a scroll bar to the news section, similar to that of the Twitter widget on the homepage?

**Comment by csae8092** [comment]
@zxenia : this could either be implemented as new template tag in [django-acdh-news](https://github.com/acdh-oeaw/django-acdh-news) or through some css-wizardry? I'd slightly prefer the second solution as it will keep djang-acdh-news more lightweight.

**Comment by zxenia** [comment]
I did try a scrollable bar for news (with css and also some custom js library), but in my opinion two scrollable elements next to each other is not a good solution (the second is twitter widget).  Looks to much  for my taste (see the attachment screenshot) . The nice look is also very much dependent on twitter widget which is  an iframe element so we can't override its css. My suggestion is to find a different solution for news display (maybe filtering by dates, or  a link to 'Older news', or by moving twitter widget down ). 
Let me know what do you think in order to proceed with this. 
If you are ok with this I can still implement this one. 
![test_scroll01](https://user-images.githubusercontent.com/11253950/27039326-f3f04330-4f8d-11e7-9560-1c14b07c0438.JPG)

**Comment by gfranzini** [comment]
Yes, you're right, it's a bit too much. I like your filter suggestion - how about a drop-down month/year filter? I can change the 'March-April 2017' entry to 'March 2017'. What do you think, @csae8092 ?

**Comment by gfranzini** [comment]
Thanks for trying out the scrollbar solution anyway, @zxenia !

**Comment by csae8092** [comment]
I'd say we keep it as it is for now. And if we'll ever run into the trouble of having thousands of of news messages we reopen this issue
